spring.application.name=Inmovision

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver

# 🔥 IMPORTANTE: usar variables de entorno
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 🔥 IMPORTANTE para Swagger en algunos casos
springdoc.swagger-ui.path=/swagger-ui.html

# 🔥 CRÍTICO para Render
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}