spring.application.name=Inmovision
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/Inmovision
spring.datasource.username=postgres
spring.datasource.password=24022006
